-- Generated chunk: local packages plus {resource_key, package_index}.
return {
    schema_version = 2,
    packages = {
        "packages/content/videos/adamant_intro",
        "packages/content/videos/broker_intro",
        "packages/content/videos/cin_nox_alpha",
        "packages/content/videos/core_research_intro",
        "packages/content/videos/cryptic_intro_part1",
        "packages/content/videos/cryptic_intro_part2",
        "packages/content/videos/cs06",
        "packages/content/videos/debrief_01",
        "packages/content/videos/debrief_02",
        "packages/content/videos/debrief_03",
        "packages/content/videos/debrief_04",
        "packages/content/videos/debrief_05",
        "packages/content/videos/debrief_06",
        "packages/content/videos/debrief_07",
        "packages/content/videos/debrief_08",
        "packages/content/videos/debrief_09",
        "packages/content/videos/debrief_10",
        "packages/content/videos/debrief_11",
        "packages/content/videos/debrief_12",
        "packages/content/videos/debrief_13",
        "packages/content/videos/debrief_14",
        "packages/content/videos/debrief_15",
        "packages/content/videos/debrief_16",
        "packages/content/videos/debrief_17",
        "packages/content/videos/debrief_nml_01",
        "packages/content/videos/debrief_nml_02",
        "packages/content/videos/debrief_nml_03",
        "packages/content/videos/hli_barbershop",
        "packages/content/videos/hli_contracts",
        "packages/content/videos/hli_crafting_station_underground",
        "packages/content/videos/hli_expeditions",
        "packages/content/videos/hli_gun_shop",
        "packages/content/videos/hli_mission_board",
        "packages/content/videos/hli_penances",
        "packages/content/videos/s1_intro",
        "packages/content/videos/voxshot_rise",
        "packages/ui/views/splash_view/splash_view",
    },
    resources = {
        { "content/videos/adamant_intro", 1 },
        { "content/videos/broker_intro", 2 },
        { "content/videos/cin_nox_alpha", 3 },
        { "content/videos/core_research_intro", 4 },
        { "content/videos/cryptic_intro_part1", 5 },
        { "content/videos/cryptic_intro_part2", 6 },
        { "content/videos/cs06", 7 },
        { "content/videos/darktide_world_intro", 37 },
        { "content/videos/debriefings/debrief_01", 8 },
        { "content/videos/debriefings/debrief_02", 9 },
        { "content/videos/debriefings/debrief_03", 10 },
        { "content/videos/debriefings/debrief_04", 11 },
        { "content/videos/debriefings/debrief_05", 12 },
        { "content/videos/debriefings/debrief_06", 13 },
        { "content/videos/debriefings/debrief_07", 14 },
        { "content/videos/debriefings/debrief_08", 15 },
        { "content/videos/debriefings/debrief_09", 16 },
        { "content/videos/debriefings/debrief_10", 17 },
        { "content/videos/debriefings/debrief_11", 18 },
        { "content/videos/debriefings/debrief_12", 19 },
        { "content/videos/debriefings/debrief_13", 20 },
        { "content/videos/debriefings/debrief_14", 21 },
        { "content/videos/debriefings/debrief_15", 22 },
        { "content/videos/debriefings/debrief_16", 23 },
        { "content/videos/debriefings/debrief_17", 24 },
        { "content/videos/debriefings/debrief_nml_01", 25 },
        { "content/videos/debriefings/debrief_nml_02", 26 },
        { "content/videos/debriefings/debrief_nml_03", 27 },
        { "content/videos/fatshark_splash", 37 },
        { "content/videos/hli_barbershop", 28 },
        { "content/videos/hli_contracts", 29 },
        { "content/videos/hli_crafting_station_underground", 30 },
        { "content/videos/hli_expeditions", 31 },
        { "content/videos/hli_gun_shop", 32 },
        { "content/videos/hli_mission_board", 33 },
        { "content/videos/hli_penances", 34 },
        { "content/videos/s1_intro", 35 },
        { "content/videos/voxshot_rise", 36 },
    },
}
