-- Generated chunk: local packages plus {resource_key, package_index}.
return {
    schema_version = 2,
    packages = {
        "content/characters/player/ogryn/first_person/base",
        "content/levels/cinematics/outro/fail/no_mans_land/world",
        "content/levels/cinematics/outro/win/outro_win_elevator/world",
        "content/levels/dust/missions/hm_strain_themes/darkness_01/theme_darkness_01_hm_strain",
        "content/levels/dust/missions/lm_scavenge_themes/toxic_gas_01/theme_toxic_gas_01_lm_scavenge",
        "content/levels/dust/missions/mission_dm_propaganda",
        "content/levels/entertainment/missions/km_heresy_themes/darkness_01/theme_darkness_01_km_heresy",
        "content/levels/entertainment/missions/mission_km_heresy",
        "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/themes/darkness/theme_darkness_128",
        "content/levels/expeditions/debug/locations/location_256m_crashed_train_001/missions/mission_location_256m_crashed_train_001",
        "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/themes/darkness/theme_darkness_sz",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/safe_zones/wastes/sz_train_turntable_001/missions/mission_sz_train_turntable_001",
        "content/levels/expeditions/traversal/wastes/tr_16m_flat_006/world",
        "content/levels/hub/hub_ship/missions/hub_ship_themes/default/theme_default_hub_ship",
        "content/levels/menus/briefing/world",
        "content/levels/prologue/missions/prologue",
        "content/levels/tank_foundry/missions/lm_cooling_themes/toxic_gas_01/theme_toxic_gas_01_lm_cooling",
        "content/levels/throneside/missions/mission_hm_complex",
        "content/levels/transit/missions/cm_habs_themes/ember_01/theme_ember_01_cm_habs",
        "content/levels/transit/missions/km_station_themes/ember_01/theme_ember_01_km_station",
        "content/levels/transit/missions/km_station_themes/toxic_gas_01/theme_toxic_gas_01_km_station",
        "content/levels/transit/missions/mission_km_station",
        "content/levels/transit/missions/mission_lm_rails",
        "content/levels/ui/barber_character_appearance/barber_character_appearance",
        "content/levels/ui/class_selection/class_selection_adamant/class_selection_adamant",
        "content/levels/ui/store/store",
        "content/levels/void/missions/mission_core_research",
        "content/levels/watertown/missions/dm_stockpile_themes/darkness_01/theme_darkness_01_dm_stockpile",
        "content/levels/watertown/missions/hm_cartel_themes/ember_01/theme_ember_01_hm_cartel",
        "content/levels/watertown/missions/mission_hm_cartel",
        "content/levels/watertown_twins/missions/mission_km_enforcer_twins",
        "content/pickups/consumables/side_mission/dataslate/dataslate_pickup_01",
        "content/pickups/pickup_assets",
        "content/weapons/enemy/ranged/chaos_traitor_guard_captain_plasma_gun_02/chaos_traitor_guard_captain_plasma_gun_02",
        "content/weapons/player/attachments/flashlights/flashlight_05/flashlight_05",
        "content/weapons/player/attachments/flashlights/flashlight_ogryn_01/flashlight_ogryn_01",
        "packages/boot_assets",
    },
    resources = {
        { "#ID[08ea67143e557a83]", 13 },
        { "#ID[10a7c4b64578b899]", 17 },
        { "#ID[134696d18a8e1d8f]", 1 },
        { "#ID[1427366aa78b8b93]", 23 },
        { "#ID[1e5b0613f33d475e]", 16 },
        { "#ID[1f81697ec98d9554]", 7 },
        { "#ID[5443baf30d9105a9]", 24 },
        { "#ID[56cba980e2d0c4c4]", 9 },
        { "#ID[6dbb8fc3478afe81]", 10 },
        { "#ID[723b529ccec2e46d]", 19 },
        { "#ID[7f7c32de3afc1cf3]", 12 },
        { "#ID[9425d5d718b94231]", 30 },
        { "#ID[b1499add08534f82]", 21 },
        { "#ID[bbcfb256822802e5]", 31 },
        { "#ID[bc924bd4047e4d1e]", 14 },
        { "#ID[ce9e915c6f6fa171]", 25 },
        { "#ID[d319490c89dbd1dd]", 17 },
        { "#ID[dbcf9b53f4b5ec36]", 37 },
        { "#ID[eb375b5781a4a966]", 27 },
        { "#ID[ffd1ce6d2435b789]", 32 },
        { "content/environment/ies_profiles/bollard", 3 },
        { "content/environment/ies_profiles/comet", 17 },
        { "content/environment/ies_profiles/defined", 34 },
        { "content/environment/ies_profiles/defineddiffuse", 35 },
        { "content/environment/ies_profiles/defineddiffusespot", 22 },
        { "content/environment/ies_profiles/definedspot", 8 },
        { "content/environment/ies_profiles/narrow/flashlight_custom_01", 39 },
        { "content/environment/ies_profiles/narrow/flashlight_custom_02", 38 },
        { "content/environment/ies_profiles/narrow/flashlight_custom_03", 2 },
        { "content/environment/ies_profiles/narrow/narrow_01", 29 },
        { "content/environment/ies_profiles/narrow/narrow_02", 18 },
        { "content/environment/ies_profiles/narrow/narrow_03", 5 },
        { "content/environment/ies_profiles/narrow/narrow_04", 20 },
        { "content/environment/ies_profiles/narrow/narrow_05", 31 },
        { "content/environment/ies_profiles/narrow/narrow_06", 26 },
        { "content/environment/ies_profiles/narrow/narrow_07", 33 },
        { "content/environment/ies_profiles/overhead", 6 },
        { "content/environment/ies_profiles/pear", 36 },
        { "content/environment/ies_profiles/round", 28 },
        { "content/environment/ies_profiles/toppost", 15 },
        { "content/environment/ies_profiles/xarrow", 4 },
        { "content/environment/ies_profiles/xarrowdiffuse", 11 },
        { "content/environment/ies_profiles/xarrowsoft", 20 },
    },
}
