-- Generated chunk: local packages plus {resource_key, package_index}.
return {
    schema_version = 2,
    packages = {
        "content/levels/cinematics/c_cams/c_cam_heresy/world",
        "content/levels/cinematics/c_cams/c_cam_train/world",
        "content/levels/cinematics/outro/fail/horde/generic/world",
        "content/levels/cinematics/outro/fail/no_mans_land/world",
        "content/levels/cinematics/outro/fail/outro_fail_generic/world",
        "content/levels/cinematics/outro/fail/tank_foundry/generic/world",
        "content/levels/cinematics/outro/fail/throneside/generic/world",
        "content/levels/cinematics/outro/fail/train/generic/world",
        "content/levels/cinematics/outro/fail/transit/generic/world",
        "content/levels/cinematics/outro/fail/void/core_research/world",
        "content/levels/cinematics/outro/fail/watertown/generic/world",
        "content/levels/cinematics/outro/fail/watertown/km_twins/outro_fail_km_twins/world",
        "content/levels/cinematics/outro/win/outro_win_core/world",
        "content/levels/cinematics/outro/win/outro_win_elevator/world",
        "content/levels/cinematics/outro/win/outro_win_fm/world",
        "content/levels/cinematics/outro/win/outro_win_generic/world",
        "content/levels/cinematics/outro/win/outro_win_horde/world",
        "content/levels/dust/missions/dm_propaganda_themes/darkness_01/theme_darkness_01_dm_propaganda",
        "content/levels/dust/missions/dm_propaganda_themes/nurgle_01/theme_nurgle_01_dm_propaganda",
        "content/levels/dust/missions/dm_propaganda_themes/toxic_gas_01/theme_toxic_gas_01_dm_propaganda",
        "content/levels/dust/missions/hm_strain_themes/darkness_01/theme_darkness_01_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/ember_01/theme_ember_01_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/nurgle_01/theme_nurgle_01_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/toxic_gas_01/theme_toxic_gas_01_hm_strain",
        "content/levels/dust/missions/lm_scavenge_themes/darkness_01/theme_darkness_01_lm_scavenge",
        "content/levels/dust/missions/lm_scavenge_themes/default/theme_default_lm_scavenge",
        "content/levels/dust/missions/lm_scavenge_themes/toxic_gas_01/theme_toxic_gas_01_lm_scavenge",
        "content/levels/dust/missions/mission_dm_propaganda",
        "content/levels/dust/missions/mission_hm_strain",
        "content/levels/dust/missions/mission_lm_scavenge",
        "content/levels/entertainment/missions/cm_raid_themes/darkness_01/theme_darkness_01_cm_raid",
        "content/levels/entertainment/missions/cm_raid_themes/toxic_gas_01/theme_toxic_gas_01_cm_raid",
        "content/levels/entertainment/missions/cm_raid_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_raid",
        "content/levels/entertainment/missions/fm_armoury_themes/darkness_01/theme_darkness_01_fm_armoury",
        "content/levels/entertainment/missions/fm_armoury_themes/default/theme_default_fm_armoury",
        "content/levels/entertainment/missions/fm_armoury_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_armoury",
        "content/levels/entertainment/missions/km_heresy_themes/darkness_01/theme_darkness_01_km_heresy",
        "content/levels/entertainment/missions/km_heresy_themes/ventilation_purge_01/theme_ventilation_purge_01_km_heresy",
        "content/levels/entertainment/missions/mission_cm_raid",
        "content/levels/entertainment/missions/mission_fm_armoury",
        "content/levels/entertainment/missions/mission_km_heresy",
        "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/location_128m_theme_test_001",
        "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/themes/darkness/theme_darkness_128",
        "content/levels/expeditions/debug/locations/location_256_chasm_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/safezone_theme_test_001",
        "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/themes/darkness/theme_darkness_sz",
        "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/opportunities/wastes/op_64m_luggable_building_001/world",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/start/world",
        "content/levels/expeditions/traversal/wastes/tr_16m_flat_004/world",
        "content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_destroyed_002/world",
        "content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_makeshift_003/world",
        "content/levels/horde/missions/mission_psykhanium",
        "content/levels/hub/hub_ship/cinematics/hub_location_intros/hli_mission_terminal/world",
        "content/levels/hub/hub_ship/cinematics/hub_location_intros/hli_training_grounds/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_bar/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_barracks/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_corridor_01/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_corridor_02/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_hangar/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_office/world",
        "content/levels/hub/hub_ship/cinematics/path_of_trust/pot_war_room/world",
        "content/levels/hub/hub_ship/cs_07_08_office/world",
        "content/levels/hub/hub_ship/missions/hub_ship_themes/hub_anniversary_01/theme_hub_anniversary",
        "content/levels/hub/hub_ship/missions/hub_ship_themes/hub_skulls_01/theme_hub_skulls",
        "content/levels/menus/briefing/world",
        "content/levels/operations/no_mans_land/missions/mission_op_no_mans_land",
        "content/levels/operations/train/missions/mission_op_train",
        "content/levels/prologue/cs_01_exterior/world",
        "content/levels/prologue/cs_03_bay/world",
        "content/levels/prologue/cs_04_hangar/world",
        "content/levels/prologue/cs_05_exterior/world",
        "content/levels/prologue/cs_05_hangar/world",
        "content/levels/prologue/cs_05_hub/world",
        "content/levels/prologue/missions/prologue",
        "content/levels/tank_foundry/missions/dm_forge_themes/darkness_01/theme_darkness_01_dm_forge",
        "content/levels/tank_foundry/missions/dm_forge_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_forge",
        "content/levels/tank_foundry/missions/fm_cargo_themes/darkness_01/theme_darkness_01_fm_cargo",
        "content/levels/tank_foundry/missions/fm_cargo_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_cargo",
        "content/levels/tank_foundry/missions/lm_cooling_themes/darkness_01/theme_darkness_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/toxic_gas_01/theme_toxic_gas_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/ventilation_purge_01/theme_ventilation_purge_01_lm_cooling",
        "content/levels/tank_foundry/missions/mission_dm_forge",
        "content/levels/tank_foundry/missions/mission_fm_cargo",
        "content/levels/tank_foundry/missions/mission_lm_cooling",
        "content/levels/throneside/missions/cm_archives_themes/darkness_01/theme_darkness_01_cm_archives",
        "content/levels/throneside/missions/cm_archives_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_archives",
        "content/levels/throneside/missions/fm_resurgence_themes/darkness_01/theme_darkness_01_fm_resurgence",
        "content/levels/throneside/missions/fm_resurgence_themes/toxic_gas_01/theme_toxic_gas_01_fm_resurgence",
        "content/levels/throneside/missions/fm_resurgence_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_resurgence",
        "content/levels/throneside/missions/hm_complex_themes/darkness_01/theme_darkness_01_hm_complex",
        "content/levels/throneside/missions/hm_complex_themes/ventilation_purge_01/theme_ventilation_purge_01_hm_complex",
        "content/levels/throneside/missions/mission_cm_archives",
        "content/levels/throneside/missions/mission_fm_resurgence",
        "content/levels/throneside/missions/mission_hm_complex",
        "content/levels/training_grounds/missions/mission_tg_basic_combat_01",
        "content/levels/transit/deck/themes/nurgle_01/theme_nurgle_01_deck",
        "content/levels/transit/hab_b/themes/nurgle_01/theme_nurgle_01_hab_b",
        "content/levels/transit/market/themes/nurgle_01/theme_nurgle_01_market",
        "content/levels/transit/missions/cm_habs_themes/darkness_01/theme_darkness_01_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/nurgle_01/theme_nurgle_01_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_habs",
        "content/levels/transit/missions/dm_rise_themes/darkness_01/theme_darkness_01_dm_rise",
        "content/levels/transit/missions/dm_rise_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_rise",
        "content/levels/transit/missions/km_station_themes/darkness_01/theme_darkness_01_km_station",
        "content/levels/transit/missions/km_station_themes/ember_01/theme_ember_01_km_station",
        "content/levels/transit/missions/km_station_themes/gas_01/theme_gas_01_km_station",
        "content/levels/transit/missions/km_station_themes/noir_01/theme_noir_01_km_station",
        "content/levels/transit/missions/km_station_themes/toxic_gas_01/theme_toxic_gas_01_km_station",
        "content/levels/transit/missions/km_station_themes/ventilation_purge_01/theme_ventilation_purge_01_km_station",
        "content/levels/transit/missions/lm_rails_themes/darkness_01/theme_darkness_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/ember_01/theme_ember_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/noir_01/theme_noir_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/ventilation_purge_01/theme_ventilation_purge_01_lm_rails",
        "content/levels/transit/missions/mission_cm_habs",
        "content/levels/transit/missions/mission_dm_rise",
        "content/levels/transit/missions/mission_km_station",
        "content/levels/transit/missions/mission_lm_rails",
        "content/levels/ui/barber_character_mindwipe/barber_character_mindwipe",
        "content/levels/ui/cartel_selection/cartel_selection",
        "content/levels/ui/character_create/character_create",
        "content/levels/ui/class_selection/class_selection_ogryn/class_selection_ogryn",
        "content/levels/ui/contracts_view/contracts_view",
        "content/levels/ui/crafting_view_itemization/crafting_view_itemization",
        "content/levels/ui/credits_cosmetics_vendor/credits_cosmetics_vendor",
        "content/levels/ui/credits_vendor/credits_vendor",
        "content/levels/ui/end_of_round/ui_eor_background",
        "content/levels/ui/expedition/world",
        "content/levels/ui/expeditions_lobby/expeditions_lobby",
        "content/levels/ui/forgeworld_selection/forgeworld_selection",
        "content/levels/ui/group_finder/group_finder",
        "content/levels/ui/horde_mission_intro/horde_mission_intro",
        "content/levels/ui/inventory_weapon_view/inventory_weapon_view",
        "content/levels/ui/main_menu/main_menu",
        "content/levels/ui/mission_board_player_journey/mission_board_player_journey",
        "content/levels/ui/mission_intro/mission_intro",
        "content/levels/ui/penances/world",
        "content/levels/ui/store/store",
        "content/levels/ui/title_screen/title_screen",
        "content/levels/ui/training_grounds/training_grounds",
        "content/levels/ui/vendor_cosmetics_preview_gear/vendor_cosmetics_preview_gear",
        "content/levels/ui/vendor_cosmetics_preview_weapon/vendor_cosmetics_preview_weapon",
        "content/levels/void/missions/core_research_themes/darkness_01/theme_darkness_01_core_research",
        "content/levels/void/missions/core_research_themes/ventilation_purge_01/theme_ventilation_purge_01_core_research",
        "content/levels/void/missions/mission_core_research",
        "content/levels/watertown/missions/dm_stockpile_themes/darkness_01/theme_darkness_01_dm_stockpile",
        "content/levels/watertown/missions/dm_stockpile_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_stockpile",
        "content/levels/watertown/missions/hm_cartel_themes/darkness_01/theme_darkness_01_hm_cartel",
        "content/levels/watertown/missions/hm_cartel_themes/toxic_gas_01/theme_toxic_gas_01_hm_cartel",
        "content/levels/watertown/missions/hm_cartel_themes/ventilation_purge_01/theme_ventilation_purge_01_hm_cartel",
        "content/levels/watertown/missions/km_enforcer_themes/darkness_01/theme_darkness_01_km_enforcer",
        "content/levels/watertown/missions/km_enforcer_themes/ventilation_purge_01/theme_ventilation_purge_01_km_enforcer",
        "content/levels/watertown/missions/mission_dm_stockpile",
        "content/levels/watertown/missions/mission_hm_cartel",
        "content/levels/watertown/missions/mission_km_enforcer",
        "content/levels/watertown_twins/missions/mission_km_enforcer_twins",
        "packages/boot_assets",
        "packages/content/live_events/stolen_rations/stolen_rations_assets",
        "packages/game_mode/expedition",
        "packages/ui/ui_signin_assets",
        "packages/ui/view_elements/view_element_inventory_weapon_preview/view_element_inventory_weapon_preview",
        "packages/ui/views/barber_vendor_background_view/barber_vendor_background_view",
        "packages/ui/views/custom_settings_view/custom_settings_view",
        "packages/ui/views/marks_vendor_view/marks_vendor_view",
    },
    resources = {
        { "#ID[0b8ba01c8b284e35]", 180 },
        { "#ID[17cd6213e7494a81]", 179 },
        { "#ID[54a9b9dc2a11bd38]", 175 },
        { "#ID[54dca56c7c0b7a96]", 173 },
        { "#ID[904b85f4730deff7]", 0 },
        { "content/levels/cinematics/cinematic_shade_envs/gunshop_hub", 70 },
        { "content/levels/debug/artlevels/sara/test_zone/shading_environments/test_mission_elevator_void", 161 },
        { "content/shading_environments/artscenes/throneside_shading_environment", 110 },
        { "content/shading_environments/artscenes/void_artscene_01", 4 },
        { "content/shading_environments/briefing_01", 82 },
        { "content/shading_environments/default_worklight_01", 83 },
        { "content/shading_environments/dust/mission_cm_strain/circumstances/darkness_01/dust_mission_hm_strain_darkness_01", 43 },
        { "content/shading_environments/dust/mission_cm_strain/circumstances/darkness_01/dust_mission_hm_strain_darkness_01_vista", 21 },
        { "content/shading_environments/dust/mission_cm_strain/circumstances/nurgle/dust_mission_hm_strain_nurgle_01", 23 },
        { "content/shading_environments/dust/mission_cm_strain/circumstances/toxic_gas_01/dust_hm_strain_indoor_toxic_gas_01", 24 },
        { "content/shading_environments/dust/mission_cm_strain/circumstances/toxic_gas_01/dust_hm_strain_start_strain_vista_toxic_gas_01", 24 },
        { "content/shading_environments/dust/mission_cm_strain/circumstances/toxic_gas_01/dust_hm_strain_vista_toxic_gas_01", 24 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_cm_strain_dust_junction_01", 29 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_cm_strain_surveillance_01", 29 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_hm_strain_01", 29 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_hm_strain_fuel_depot_01", 29 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_hm_strain_intro_c_cam_01", 29 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_hm_strain_outro_win_01", 29 },
        { "content/shading_environments/dust/mission_cm_strain/dust_mission_hm_strain_start_strain_01", 29 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/darkness_01/dust_mission_lm_scavenge_darkness_01", 25 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/darkness_01/dust_mission_lm_scavenge_darkness_01_vista", 25 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/toxic_gas_01/dust_lm_scavenge_elevator_bake_toxic_gas_01", 27 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/toxic_gas_01/dust_lm_scavenge_indoor_toxic_gas_01", 27 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/toxic_gas_01/dust_lm_scavenge_outdoor_toxic_gas_01", 27 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/toxic_gas_01/dust_lm_scavenge_ship_port_toxic_gas_01", 27 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/toxic_gas_01/dust_lm_scavenge_ship_port_toxic_gas_02", 27 },
        { "content/shading_environments/dust/mission_ct_scavenge/circumstances/toxic_gas_01/dust_lm_scavenge_vista_toxic_gas_01", 27 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_consulate_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_consulate_elevator_bake_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_end_scavenge_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_intro_c_cam_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_outro_win_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_personal_vaults_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_security_office_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_ship_elevator_01", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_ship_elevator_02", 30 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_ship_port_01", 26 },
        { "content/shading_environments/dust/mission_ct_scavenge/dust_mission_ct_scavenge_start_scavenge_01", 30 },
        { "content/shading_environments/dust/mission_dm_propaganda/circumstances/darkness_01/dust_mission_dm_propaganda_darkness_01", 18 },
        { "content/shading_environments/dust/mission_dm_propaganda/circumstances/darkness_01/dust_mission_dm_propaganda_darkness_01_vista", 18 },
        { "content/shading_environments/dust/mission_dm_propaganda/circumstances/nurgle/dust_mission_dm_propaganda_nurgle_01", 19 },
        { "content/shading_environments/dust/mission_dm_propaganda/circumstances/toxic_gas_01/dust_mission_dm_propaganda_toxic_gas_01_indoor", 20 },
        { "content/shading_environments/dust/mission_dm_propaganda/circumstances/toxic_gas_01/dust_mission_dm_propaganda_toxic_gas_01_vista", 20 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_01", 45 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_command_01", 28 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_command_02", 28 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_intro_c_cam_01", 28 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_outro_win_01", 28 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_start_propaganda_01", 28 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_start_propaganda_02", 28 },
        { "content/shading_environments/dust/mission_dm_propaganda/dust_mission_dm_propaganda_trenches_01", 29 },
        { "content/shading_environments/entertainment/entertainment_worklight", 131 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/darkness_01/entertainment_cm_raid_darkness_01", 31 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/darkness_01/entertainment_cm_raid_drug_lab_darkness_01", 31 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/toxic_gas_01/entertainment_cm_raid_drug_lab_toxic_gas_01", 32 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/toxic_gas_01/entertainment_cm_raid_obscura_den_toxic_gas_01", 32 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/toxic_gas_01/entertainment_cm_raid_toxic_gas_01", 32 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/ventilation_purge_01/entertainment_cm_raid_drug_lab_ventilation_purge_01", 33 },
        { "content/shading_environments/entertainment/mission_cm_raid/circumstances/ventilation_purge_01/entertainment_cm_raid_ventilation_purge_01", 33 },
        { "content/shading_environments/entertainment/mission_cm_raid/entertainment_mission_cm_raid_01", 39 },
        { "content/shading_environments/entertainment/mission_cm_raid/entertainment_mission_cm_raid_drug_lab_01", 39 },
        { "content/shading_environments/entertainment/mission_cm_raid/entertainment_mission_cm_raid_outro_win_01", 39 },
        { "content/shading_environments/entertainment/mission_cm_raid/entertainment_mission_cm_raid_start_raid_01", 39 },
        { "content/shading_environments/entertainment/mission_cm_raid/entertainment_mission_cm_raid_uptown_01", 39 },
        { "content/shading_environments/entertainment/mission_fm_armoury/circumstances/darkness_01/entertainment_fm_armoury_darkness_01", 34 },
        { "content/shading_environments/entertainment/mission_fm_armoury/circumstances/ventilation_purge_01/entertainment_mission_fm_armoury_distribution_ventilation_purge_01", 36 },
        { "content/shading_environments/entertainment/mission_fm_armoury/circumstances/ventilation_purge_01/entertainment_mission_fm_armoury_ventilation_purge_01", 36 },
        { "content/shading_environments/entertainment/mission_fm_armoury/entertainment_mission_fm_armoury_01", 35 },
        { "content/shading_environments/entertainment/mission_fm_armoury/entertainment_mission_fm_armoury_diner_event_01", 40 },
        { "content/shading_environments/entertainment/mission_fm_armoury/entertainment_mission_fm_armoury_distribution_01", 40 },
        { "content/shading_environments/entertainment/mission_fm_armoury/entertainment_mission_fm_armoury_start_armoury_01", 40 },
        { "content/shading_environments/entertainment/mission_km_heresy/circumstances/darkness_01/entertainment_km_heresy_darkness_01", 37 },
        { "content/shading_environments/entertainment/mission_km_heresy/circumstances/darkness_01/entertainment_km_heresy_rooftops_darkness_01", 46 },
        { "content/shading_environments/entertainment/mission_km_heresy/circumstances/ventilation_purge_01/entertainment_km_heresy_ventilation_purge_01", 38 },
        { "content/shading_environments/entertainment/mission_km_heresy/entertainment_mission_km_heresy_01", 1 },
        { "content/shading_environments/entertainment/mission_km_heresy/entertainment_mission_km_heresy_cathedral_01", 41 },
        { "content/shading_environments/entertainment/mission_km_heresy/entertainment_mission_km_heresy_cathedral_bridge_01", 41 },
        { "content/shading_environments/entertainment/mission_km_heresy/entertainment_mission_km_heresy_cellar_01", 40 },
        { "content/shading_environments/entertainment/mission_km_heresy/entertainment_mission_km_heresy_rooftops_01", 41 },
        { "content/shading_environments/entertainment/mission_km_heresy/entertainment_mission_km_heresy_uptown_transition_01", 41 },
        { "content/shading_environments/expeditions/expeditions_chasm_default_01", 175 },
        { "content/shading_environments/expeditions/expeditions_darkness_01", 44 },
        { "content/shading_environments/expeditions/expeditions_default_01", 65 },
        { "content/shading_environments/expeditions/expeditions_default_indoors_01", 63 },
        { "content/shading_environments/expeditions/expeditions_test_01", 175 },
        { "content/shading_environments/expeditions/expeditions_test_02", 175 },
        { "content/shading_environments/expeditions/wastes/cinematics/expeditions_wastes_mission_intro_darkness", 175 },
        { "content/shading_environments/expeditions/wastes/cinematics/expeditions_wastes_mission_intro_dawn", 175 },
        { "content/shading_environments/expeditions/wastes/cinematics/expeditions_wastes_mission_intro_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_airlock_01", 68 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_airlock_blackout_01", 68 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_airlock_transition_01", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_chasm_002_darkness", 49 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_chasm_002_dawn", 50 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_chasm_002_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_chasm_default", 66 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_001_darkness", 51 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_001_dawn", 52 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_001_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_001_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_002_darkness", 53 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_002_dawn", 54 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_002_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_002_high_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_002_low_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_chasm_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_darkness", 55 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_dawn", 56 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_high_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_low_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_colony_003_mid_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_covered_dsl_01", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_dawn_indoor_01", 48 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_indoor_01", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_no_probes_01", 67 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_oil_darkness_01", 47 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_oil_dawn_01", 48 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_oil_default_01", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_001_darkness_01", 57 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_001_dawn_01", 58 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_001_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_003_darkness", 59 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_003_dawn", 60 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_003_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_003_high_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_003_low_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_ravine_003_mid_ground_fog", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_safezone_01", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_safezone_dawn_01", 64 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_underpass_001_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_underpass_002_darkness", 61 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_underpass_002_dawn", 62 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_underpass_002_default", 175 },
        { "content/shading_environments/expeditions/wastes/expeditions_wastes_underpass_002_default_02", 175 },
        { "content/shading_environments/foundry/mission_ct_cooling/circumstances/darkness_01/tank_foundry_lm_cooling_darkness_01", 96 },
        { "content/shading_environments/foundry/mission_ct_cooling/circumstances/toxic_gas_01/tank_foundry_lm_cooling_outdoor_toxic_gas_01", 97 },
        { "content/shading_environments/foundry/mission_ct_cooling/circumstances/toxic_gas_01/tank_foundry_lm_cooling_toxic_gas_01", 97 },
        { "content/shading_environments/foundry/mission_ct_cooling/circumstances/ventilation_purge_01/tank_foundry_mission_lm_cooling_ventilation_purge_01", 98 },
        { "content/shading_environments/foundry/mission_ct_cooling/circumstances/ventilation_purge_01/tank_foundry_mission_lm_cooling_ventilation_purge_01_indoor_low", 98 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_cooling_shaft_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_end_cooling_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_forge_habs_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_intro_c_cam_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_outro_win_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_reactor_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_reactor_fade_01", 101 },
        { "content/shading_environments/foundry/mission_ct_cooling/tank_foundry_mission_ct_cooling_start_cooling_01", 101 },
        { "content/shading_environments/foundry/mission_dm_forge/circumstances/darkness_01/tank_foundry_dm_forge_darkness_01", 92 },
        { "content/shading_environments/foundry/mission_dm_forge/circumstances/ventilation_purge_01/tank_foundry_mission_dm_forge_ventilation_purge_01", 93 },
        { "content/shading_environments/foundry/mission_dm_forge/circumstances/ventilation_purge_01/tank_foundry_mission_dm_forge_ventilation_purge_01_vista", 93 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_01", 101 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_dust_arrival_01", 99 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_foundry_01", 99 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_furnace_01", 6 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_intro_c_cam_01", 99 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_outro_win_01", 99 },
        { "content/shading_environments/foundry/mission_dm_forge/tank_foundry_mission_dm_forge_workers_hub_01", 100 },
        { "content/shading_environments/foundry/mission_fm_cargo/circumstances/darkness_01/tank_foundry_mission_fm_cargo_darkness_01", 94 },
        { "content/shading_environments/foundry/mission_fm_cargo/circumstances/darkness_01/tank_foundry_mission_fm_cargo_darkness_01_vista", 94 },
        { "content/shading_environments/foundry/mission_fm_cargo/circumstances/ventilation_purge_01/tank_foundry_mission_fm_cargo_ventilation_purge_01", 95 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_01", 100 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_cargo_approach_01", 100 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_intro_c_cam_01", 100 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_loading_bay_01", 100 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_outro_win_01", 15 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_processing_01", 100 },
        { "content/shading_environments/foundry/mission_fm_cargo/tank_foundry_mission_fm_cargo_workers_section_01", 100 },
        { "content/shading_environments/horde/horde_01", 17 },
        { "content/shading_environments/horde/horde_island_lobby_01", 3 },
        { "content/shading_environments/horde/horde_island_machine_01", 69 },
        { "content/shading_environments/horde/horde_rooftops_01", 69 },
        { "content/shading_environments/hub/circumstances/anniversary_01/hub_theme_anniversary_01", 80 },
        { "content/shading_environments/hub/circumstances/skulls_01/hub_theme_skulls_01", 81 },
        { "content/shading_environments/hub/hub_default_01", 79 },
        { "content/shading_environments/hub/hub_hub_ship_01", 71 },
        { "content/shading_environments/hub/path_of_trust/pot_bar_01", 72 },
        { "content/shading_environments/hub/path_of_trust/pot_barracks_01", 73 },
        { "content/shading_environments/hub/path_of_trust/pot_corridor_01", 74 },
        { "content/shading_environments/hub/path_of_trust/pot_corridor_02", 75 },
        { "content/shading_environments/hub/path_of_trust/pot_crafting_station_01", 90 },
        { "content/shading_environments/hub/path_of_trust/pot_hangar_01", 76 },
        { "content/shading_environments/hub/path_of_trust/pot_inquisitor_office_01", 77 },
        { "content/shading_environments/hub/path_of_trust/pot_war_room_01", 78 },
        { "content/shading_environments/moods/adamant_charge_mood", 173 },
        { "content/shading_environments/moods/broker_gunslinger_focus_mood", 173 },
        { "content/shading_environments/moods/broker_punk_rage_mood", 173 },
        { "content/shading_environments/moods/corruptor_proximity_mood", 173 },
        { "content/shading_environments/moods/critical_health_mood", 173 },
        { "content/shading_environments/moods/cryptic_personal_force_field_mood", 173 },
        { "content/shading_environments/moods/damage_hit_mood", 173 },
        { "content/shading_environments/moods/horde_story_echo_mood", 173 },
        { "content/shading_environments/moods/knocked_down_mood", 173 },
        { "content/shading_environments/moods/last_wound_mood", 173 },
        { "content/shading_environments/moods/no_toughness_mood", 173 },
        { "content/shading_environments/moods/ogryn_charge_mood", 173 },
        { "content/shading_environments/moods/ogryn_taunt_mood", 173 },
        { "content/shading_environments/moods/psyker_shout_mood", 173 },
        { "content/shading_environments/moods/stealth_mood", 173 },
        { "content/shading_environments/moods/stimms_concentration_yellow_mood_01", 173 },
        { "content/shading_environments/moods/stimms_power_red_mood_01", 173 },
        { "content/shading_environments/moods/stimms_speed_blue_mood_01", 173 },
        { "content/shading_environments/moods/suppression_high_mood", 173 },
        { "content/shading_environments/moods/suppression_low_mood", 173 },
        { "content/shading_environments/moods/suppression_mood", 173 },
        { "content/shading_environments/moods/thoughness_broken_mood", 173 },
        { "content/shading_environments/moods/veteran_combat_ability_mood", 173 },
        { "content/shading_environments/moods/veteran_stealth_mood", 173 },
        { "content/shading_environments/moods/zealot_dash_mood", 173 },
        { "content/shading_environments/operations/no_mans_land/no_mans_land_trenches_01", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_01", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_02", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_bastion_ritual_01", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_bastion_ritual_02", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_dead_zone_01", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_dead_zone_02", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_dead_zone_03", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_dead_zone_transition_01", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_dead_zone_transition_sun_off", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_ruined_archway_01", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_ruined_archway_02", 83 },
        { "content/shading_environments/operations/no_mans_land/op_mission_op_no_mans_land_ruins_basement_01", 83 },
        { "content/shading_environments/operations/train/op_mission_op_train_01", 2 },
        { "content/shading_environments/operations/train/op_train_outro_fail", 8 },
        { "content/shading_environments/prologue/prologue_cellblock_01", 91 },
        { "content/shading_environments/prologue/prologue_cs_01_exterior_01", 85 },
        { "content/shading_environments/prologue/prologue_cs_03_bay", 86 },
        { "content/shading_environments/prologue/prologue_cs_04_hangar", 87 },
        { "content/shading_environments/prologue/prologue_cs_05_exterior", 88 },
        { "content/shading_environments/prologue/prologue_cs_05_exterior_02", 88 },
        { "content/shading_environments/prologue/prologue_cs_05_exterior_03", 88 },
        { "content/shading_environments/prologue/prologue_cs_05_exterior_04", 88 },
        { "content/shading_environments/prologue/prologue_cs_05_hangar", 89 },
        { "content/shading_environments/prologue/prologue_cs_cells_01", 91 },
        { "content/shading_environments/throneside/mission_cm_archives/circumstances/darkness_01/throneside_mission_cm_archives_darkness_01_inside", 102 },
        { "content/shading_environments/throneside/mission_cm_archives/circumstances/throneside_mission_cm_archives_darkness_01", 102 },
        { "content/shading_environments/throneside/mission_cm_archives/circumstances/ventilation_purge_01/throneside_mission_cm_archives_ventilation_purge_01", 103 },
        { "content/shading_environments/throneside/mission_cm_archives/circumstances/ventilation_purge_01/throneside_mission_cm_archives_ventilation_purge_01_vista", 103 },
        { "content/shading_environments/throneside/mission_cm_archives/mission_cm_archives_01", 109 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_01", 7 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_abscondium_01", 109 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_archives_deep_01", 109 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_archives_outside_01", 109 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_intro_c_cam_01", 109 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_outro_win_01", 14 },
        { "content/shading_environments/throneside/mission_cm_archives/throneside_mission_cm_archives_start_archives_01", 109 },
        { "content/shading_environments/throneside/mission_fm_resurgence/circumstances/darkness/throneside_mission_fm_resurgence_darkness_01", 104 },
        { "content/shading_environments/throneside/mission_fm_resurgence/circumstances/toxic_gas_01/throneside_mission_fm_resurgence_toxic_gas_01", 105 },
        { "content/shading_environments/throneside/mission_fm_resurgence/circumstances/ventilation_purge_01/throneside_mission_fm_resurgence_ventilation_purge_01", 106 },
        { "content/shading_environments/throneside/mission_fm_resurgence/circumstances/ventilation_purge_01/throneside_mission_fm_resurgence_ventilation_purge_01_vista", 106 },
        { "content/shading_environments/throneside/mission_fm_resurgence/throneside_mission_fm_resurgence_01", 111 },
        { "content/shading_environments/throneside/mission_fm_resurgence/throneside_mission_fm_resurgence_approach_01", 110 },
        { "content/shading_environments/throneside/mission_fm_resurgence/throneside_mission_fm_resurgence_archives_outside_01", 110 },
        { "content/shading_environments/throneside/mission_fm_resurgence/throneside_mission_fm_resurgence_intro_c_cam_01", 110 },
        { "content/shading_environments/throneside/mission_fm_resurgence/throneside_mission_fm_resurgence_outro_win_01", 110 },
        { "content/shading_environments/throneside/mission_hm_complex/circumstances/darkness_01/throneside_mission_hm_complex_darkness_01_inside", 107 },
        { "content/shading_environments/throneside/mission_hm_complex/circumstances/darkness_01/throneside_mission_hm_complex_darkness_01_outside", 107 },
        { "content/shading_environments/throneside/mission_hm_complex/circumstances/ventilation_purge_01/throneside_mission_hm_complex_ventilation_purge_01", 108 },
        { "content/shading_environments/throneside/mission_hm_complex/circumstances/ventilation_purge_01/throneside_mission_hm_complex_ventilation_purge_01_outdoor_low", 108 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_01", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_admin_office_01", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_intro_c_cam_01", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_lobby_01", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_lobby_02", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_outro_win_01", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_start_complex_01", 111 },
        { "content/shading_environments/throneside/mission_hm_complex/throneside_mission_hm_complex_summit_01", 111 },
        { "content/shading_environments/training_grounds/tg_basic_combat_01/training_grounds_basic_combat_01", 112 },
        { "content/shading_environments/training_grounds/tg_basic_combat_01/training_grounds_basic_combat_02", 112 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/darkness/transit_mission_cm_habs_darkness_01", 116 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/nurgle/transit_mission_cm_habs_nurgle_indoor_01", 115 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/nurgle/transit_mission_cm_habs_nurgle_indoor_top_01", 117 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/nurgle/transit_mission_cm_habs_nurgle_outdoor_01", 113 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/nurgle/transit_mission_cm_habs_nurgle_vista_01", 123 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/ventilation_purge_01/transit_mission_cm_habs_ventilation_purge_01", 118 },
        { "content/shading_environments/transit/mission_cm_habs/circumstances/ventilation_purge_01/transit_mission_cm_habs_ventilation_purge_01_vista", 118 },
        { "content/shading_environments/transit/mission_cm_habs/mission_cm_habs_hab_b_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_01", 9 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_deck_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_hab_a_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_hab_shaft_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_intro_c_cam_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_lobby_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_outro_win_01", 131 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_streets_01", 134 },
        { "content/shading_environments/transit/mission_cm_habs/transit_mission_cm_habs_void_01", 131 },
        { "content/shading_environments/transit/mission_dm_rise/circumstances/darkness/transit_mission_dm_rise_darkness_01", 119 },
        { "content/shading_environments/transit/mission_dm_rise/circumstances/ventilation_purge/transit_mission_dm_rise_ventilation_purge_01", 120 },
        { "content/shading_environments/transit/mission_dm_rise/transit_mission_dm_rise_01", 132 },
        { "content/shading_environments/transit/mission_dm_rise/transit_mission_dm_rise_intro_c_cam_01", 132 },
        { "content/shading_environments/transit/mission_dm_rise/transit_mission_dm_rise_shaft_escape_01", 132 },
        { "content/shading_environments/transit/mission_dm_rise/transit_mission_dm_rise_start_rise_01", 132 },
        { "content/shading_environments/transit/mission_km_station/circumstances/darkness/transit_mission_km_station_darkness_01", 121 },
        { "content/shading_environments/transit/mission_km_station/circumstances/ember_01/transit_mission_km_station_start_ember_01", 122 },
        { "content/shading_environments/transit/mission_km_station/circumstances/gas/transit_mission_km_station_gas_indoor_top_01", 123 },
        { "content/shading_environments/transit/mission_km_station/circumstances/gas/transit_mission_km_station_gas_outdoor_01", 123 },
        { "content/shading_environments/transit/mission_km_station/circumstances/noir/transit_mission_km_station_noir_01", 124 },
        { "content/shading_environments/transit/mission_km_station/circumstances/noir/transit_mission_km_station_noir_indoor_01", 124 },
        { "content/shading_environments/transit/mission_km_station/circumstances/noir/transit_mission_km_station_noir_indoor_top_01", 124 },
        { "content/shading_environments/transit/mission_km_station/circumstances/noir/transit_mission_km_station_noir_outdoor_01", 124 },
        { "content/shading_environments/transit/mission_km_station/circumstances/noir/transit_mission_km_station_noir_vista_01", 124 },
        { "content/shading_environments/transit/mission_km_station/circumstances/toxic_gas_01/transit_mission_km_station_market_toxic_gas_01", 125 },
        { "content/shading_environments/transit/mission_km_station/circumstances/toxic_gas_01/transit_mission_km_station_toxic_gas_01", 125 },
        { "content/shading_environments/transit/mission_km_station/circumstances/ventilation_purge/transit_mission_km_station_ventilation_purge_01", 126 },
        { "content/shading_environments/transit/mission_km_station/circumstances/ventilation_purge/transit_mission_km_station_ventilation_purge_vista_01", 126 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_intro_c_cam_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_market_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_outro_win_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_pipe_maintenance_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_start_trench_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_station_inside_01", 133 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_station_outside_01", 134 },
        { "content/shading_environments/transit/mission_km_station/transit_mission_km_station_station_platform_01", 133 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/darkness/transit_mission_lm_rails_darkness_01", 127 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/darkness/transit_mission_lm_rails_darkness_01_vista", 127 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/ember/transit_mission_lm_rails_ember_01", 22 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/ember/transit_mission_lm_rails_ember_01_vista", 22 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/ember/transit_mission_lm_rails_start_ember_01", 128 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/noir/transit_mission_lm_rails_noir_01", 129 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/noir/transit_mission_lm_rails_noir_01_vista", 129 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/ventilation_purge/transit_mission_lm_rails_ventilation_purge_01", 130 },
        { "content/shading_environments/transit/mission_lm_rails/circumstances/ventilation_purge/transit_mission_lm_rails_ventilation_purge_01_vista", 130 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_01", 174 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_intro_c_cam_01", 134 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_junction_01", 134 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_outro_win_01", 134 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_precipice_01", 134 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_start_alley_01", 134 },
        { "content/shading_environments/transit/mission_lm_rails/transit_mission_lm_rails_tunnels_01", 134 },
        { "content/shading_environments/ui/barber", 178 },
        { "content/shading_environments/ui/barber_character_appearance", 135 },
        { "content/shading_environments/ui/cartel_selection", 136 },
        { "content/shading_environments/ui/character_create", 137 },
        { "content/shading_environments/ui/class_selection", 138 },
        { "content/shading_environments/ui/contracts_view", 139 },
        { "content/shading_environments/ui/crafting_view", 140 },
        { "content/shading_environments/ui/credits_cosmetics_vendor", 141 },
        { "content/shading_environments/ui/credits_vendor", 142 },
        { "content/shading_environments/ui/forge_world_selection", 146 },
        { "content/shading_environments/ui/group_finder", 147 },
        { "content/shading_environments/ui/havoc", 144 },
        { "content/shading_environments/ui/horde_mission_intro", 148 },
        { "content/shading_environments/ui/inventory", 149 },
        { "content/shading_environments/ui/lobby", 145 },
        { "content/shading_environments/ui/main_menu", 150 },
        { "content/shading_environments/ui/mission_board", 151 },
        { "content/shading_environments/ui/mission_intro", 152 },
        { "content/shading_environments/ui/mission_outro_fail", 5 },
        { "content/shading_environments/ui/mission_outro_fail_entertainment_generic", 40 },
        { "content/shading_environments/ui/outro_elevator", 16 },
        { "content/shading_environments/ui/penance_view", 153 },
        { "content/shading_environments/ui/portrait", 176 },
        { "content/shading_environments/ui/store", 154 },
        { "content/shading_environments/ui/story_mission_background", 147 },
        { "content/shading_environments/ui/system_menu", 176 },
        { "content/shading_environments/ui/title_screen", 155 },
        { "content/shading_environments/ui/training_grounds", 156 },
        { "content/shading_environments/ui/ui_eor_background", 143 },
        { "content/shading_environments/ui/ui_item_preview", 177 },
        { "content/shading_environments/ui/ui_popup_background", 0 },
        { "content/shading_environments/ui/vendor_cosmetics_preview_gear", 157 },
        { "content/shading_environments/ui/vendor_cosmetics_preview_weapon", 158 },
        { "content/shading_environments/ui/weapon_icons", 176 },
        { "content/shading_environments/ui_default", 0 },
        { "content/shading_environments/ui_default_bloom", 151 },
        { "content/shading_environments/void/mission_core_research/circumstances/darkness_01/void_core_research_darkness_01", 46 },
        { "content/shading_environments/void/mission_core_research/circumstances/darkness_01/void_core_research_darkness_01_outdoor", 159 },
        { "content/shading_environments/void/mission_core_research/circumstances/darkness_01/void_core_research_darkness_01_outdoor_top", 159 },
        { "content/shading_environments/void/mission_core_research/circumstances/darkness_01/void_core_research_darkness_01_vista", 159 },
        { "content/shading_environments/void/mission_core_research/circumstances/ventilation_purge/void_core_research_ventilation_purge_default", 160 },
        { "content/shading_environments/void/mission_core_research/circumstances/ventilation_purge/void_core_research_ventilation_purge_outdoor", 160 },
        { "content/shading_environments/void/mission_core_research/circumstances/ventilation_purge/void_core_research_ventilation_purge_outdoor_top", 160 },
        { "content/shading_environments/void/mission_core_research/circumstances/ventilation_purge/void_core_research_ventilation_purge_vista", 160 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_01", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_02", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_machine_excavation_01", 42 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_machine_excavation_02", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_machine_excavation_ice_01", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_machine_inside_01", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_outro_fail_01", 10 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_research_station_01", 84 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_respawn_blackout_01", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_start_core_research_01", 13 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_transport_backdrop_01", 161 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_void_detour_01", 84 },
        { "content/shading_environments/void/mission_core_research/void_mission_core_research_void_pillars_transition_01", 161 },
        { "content/shading_environments/watertown/mission_dm_stockpile/circumstances/darkness/watertown_dm_stockpile_darkness_01", 162 },
        { "content/shading_environments/watertown/mission_dm_stockpile/circumstances/ventilation_purge/watertown_mission_dm_stockpile_ventilation_purge_01", 163 },
        { "content/shading_environments/watertown/mission_dm_stockpile/circumstances/ventilation_purge/watertown_mission_dm_stockpile_ventilation_purge_01_vista", 163 },
        { "content/shading_environments/watertown/mission_dm_stockpile/watertown_mission_dm_stockpile_01", 169 },
        { "content/shading_environments/watertown/mission_dm_stockpile/watertown_mission_dm_stockpile_intro_c_cam_01", 169 },
        { "content/shading_environments/watertown/mission_dm_stockpile/watertown_mission_dm_stockpile_outro_win_01", 169 },
        { "content/shading_environments/watertown/mission_dm_stockpile/watertown_mission_dm_stockpile_start_stockpile_01", 169 },
        { "content/shading_environments/watertown/mission_dm_stockpile/watertown_mission_dm_stockpile_stockpile_01", 169 },
        { "content/shading_environments/watertown/mission_hm_cartel/circumstances/darkness_01/watertown_hm_cartel_darkness_01", 164 },
        { "content/shading_environments/watertown/mission_hm_cartel/circumstances/toxic_gas_01/watertown_hm_cartel_toxic_gas_01", 165 },
        { "content/shading_environments/watertown/mission_hm_cartel/circumstances/ventilation_purge_01/watertown_mission_hm_cartel_ventilation_purge_01", 166 },
        { "content/shading_environments/watertown/mission_hm_cartel/circumstances/ventilation_purge_01/watertown_mission_hm_cartel_ventilation_purge_01_vista", 166 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_01", 172 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_bazaar_01", 170 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_cartel_hq_01", 170 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_data_center_01", 170 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_intro_c_cam_01", 170 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_outro_win_01", 170 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_pipe_slum_01", 170 },
        { "content/shading_environments/watertown/mission_hm_cartel/watertown_mission_hm_cartel_start_cartel_01", 170 },
        { "content/shading_environments/watertown/mission_km_enforcer/circumstances/darkness/watertown_mission_km_enforcer_darkness_01", 167 },
        { "content/shading_environments/watertown/mission_km_enforcer/circumstances/ventilation_purge_01/watertown_mission_km_enforcer_ventilation_purge_01", 168 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_01", 11 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_enforcer_station_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_flooded_maintenance_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_flooded_slum_01", 171 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_intro_c_cam_01", 171 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_outro_win_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_prison_01", 171 },
        { "content/shading_environments/watertown/mission_km_enforcer/watertown_mission_km_enforcer_start_enforcer_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_basement_01", 12 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_enforcer_station_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_flooded_maintenance_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_flooded_slum_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_intro_c_cam_01", 172 },
        { "content/shading_environments/watertown/mission_km_enforcer_twins/watertown_mission_km_enforcer_twins_start_enforcer_01", 172 },
        { "core/stingray_renderer/environments/default/default", 114 },
    },
}
