-- Generated chunk: local packages plus {resource_key, package_index}.
return {
    schema_version = 2,
    packages = {
    },
    resources = {
        { "core/stingray_renderer/shader_libraries/bitonic_sort", 0 },
        { "core/stingray_renderer/shader_libraries/clustered_shading", 0 },
        { "core/stingray_renderer/shader_libraries/decals", 0 },
        { "core/stingray_renderer/shader_libraries/default_shaders", 0 },
        { "core/stingray_renderer/shader_libraries/development", 0 },
        { "core/stingray_renderer/shader_libraries/gui", 0 },
        { "core/stingray_renderer/shader_libraries/heatmap", 0 },
        { "core/stingray_renderer/shader_libraries/large_terrain", 0 },
        { "core/stingray_renderer/shader_libraries/large_terrain_filter_erosion", 0 },
        { "core/stingray_renderer/shader_libraries/large_terrain_utilities", 0 },
        { "core/stingray_renderer/shader_libraries/lighting", 0 },
        { "core/stingray_renderer/shader_libraries/particle_billboard", 0 },
        { "core/stingray_renderer/shader_libraries/particle_ribbon", 0 },
        { "core/stingray_renderer/shader_libraries/placeholders", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/FidelityFX/ffx_fsr", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/FidelityFX/fidelity_fx_cacao", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/FidelityFX/fidelity_fx_cas", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/auto_exposure", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/depth_of_field", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/fxaa", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/lens_flare", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/motion_blur", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/outline", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/post_processing", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/screen_space_ambient_occlusion", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/screen_space_reflections", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/screen_space_skin_filter", 0 },
        { "core/stingray_renderer/shader_libraries/post_processing/utilities", 0 },
        { "core/stingray_renderer/shader_libraries/reflection_lighting", 0 },
        { "core/stingray_renderer/shader_libraries/shadows/shadow_map", 0 },
        { "core/stingray_renderer/shader_libraries/slug", 0 },
        { "core/stingray_renderer/shader_libraries/terrain", 0 },
        { "core/stingray_renderer/shader_libraries/terrain_utilities", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxdi/rtxdi_presampling", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxgi/compute_irradiance", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxgi/compute_visualization_buffers", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxgi/ddgi/probe_blending", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxgi/ddgi/probe_border_update", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxgi/ddgi/probe_classification", 0 },
        { "core/stingray_renderer/shader_libraries/thirdparty/rtxgi/ddgi/probe_relocation", 0 },
        { "core/stingray_renderer/shader_libraries/volumetric_lighting", 0 },
        { "core/stingray_renderer/shader_libraries/water", 0 },
        { "core/stingray_renderer/shader_libraries/world_interaction", 0 },
        { "core/stingray_renderer/shader_libraries/xb1_platform", 0 },
    },
}
