-- Generated chunk: local packages plus {resource_key, package_index}.
return {
    schema_version = 2,
    packages = {
        "packages/ui/fonts/slug_ja",
        "packages/ui/fonts/slug_ko",
        "packages/ui/fonts/slug_zh_cn",
        "packages/ui/fonts/slug_zh_tw",
    },
    resources = {
        { "#ID[58e0ab534d3da5f3]", 2 },
        { "#ID[c8201df6007fec92]", 1 },
        { "#ID[dedccfc38cb9ae46]", 3 },
        { "content/ui/fonts/arial", 0 },
        { "content/ui/fonts/darktide_custom_regular", 0 },
        { "content/ui/fonts/friz_quadrata", 0 },
        { "content/ui/fonts/itc_novarese_bold", 0 },
        { "content/ui/fonts/itc_novarese_medium", 0 },
        { "content/ui/fonts/machine_medium", 0 },
        { "content/ui/fonts/mono_tide_bold", 0 },
        { "content/ui/fonts/mono_tide_light", 0 },
        { "content/ui/fonts/mono_tide_medium", 0 },
        { "content/ui/fonts/mono_tide_regular", 0 },
        { "content/ui/fonts/noto_sans_jp_black", 1 },
        { "content/ui/fonts/noto_sans_kr_black", 2 },
        { "content/ui/fonts/noto_sans_sc_black", 3 },
        { "content/ui/fonts/noto_sans_tc_black", 4 },
        { "content/ui/fonts/noto_sans_tc_bold", 4 },
        { "content/ui/fonts/proxima_nova_bold", 0 },
        { "content/ui/fonts/proxima_nova_light", 0 },
        { "content/ui/fonts/proxima_nova_medium", 0 },
        { "content/ui/fonts/rexlia", 0 },
        { "core/performance_hud/debug", 0 },
    },
}
