-- Generated chunk: local packages plus {resource_key, package_index}.
return {
    schema_version = 2,
    packages = {
        "content/levels/dust/missions/dm_propaganda_themes/darkness_01/theme_darkness_01_dm_propaganda",
        "content/levels/dust/missions/dm_propaganda_themes/default/theme_default_dm_propaganda",
        "content/levels/dust/missions/dm_propaganda_themes/nurgle_01/theme_nurgle_01_dm_propaganda",
        "content/levels/dust/missions/dm_propaganda_themes/toxic_gas_01/theme_toxic_gas_01_dm_propaganda",
        "content/levels/dust/missions/hm_strain_themes/darkness_01/theme_darkness_01_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/default/theme_default_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/ember_01/theme_ember_01_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/nurgle_01/theme_nurgle_01_hm_strain",
        "content/levels/dust/missions/hm_strain_themes/toxic_gas_01/theme_toxic_gas_01_hm_strain",
        "content/levels/dust/missions/lm_scavenge_themes/darkness_01/theme_darkness_01_lm_scavenge",
        "content/levels/dust/missions/lm_scavenge_themes/default/theme_default_lm_scavenge",
        "content/levels/dust/missions/lm_scavenge_themes/toxic_gas_01/theme_toxic_gas_01_lm_scavenge",
        "content/levels/entertainment/missions/cm_raid_themes/darkness_01/theme_darkness_01_cm_raid",
        "content/levels/entertainment/missions/cm_raid_themes/default/theme_default_cm_raid",
        "content/levels/entertainment/missions/cm_raid_themes/toxic_gas_01/theme_toxic_gas_01_cm_raid",
        "content/levels/entertainment/missions/cm_raid_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_raid",
        "content/levels/entertainment/missions/fm_armoury_themes/darkness_01/theme_darkness_01_fm_armoury",
        "content/levels/entertainment/missions/fm_armoury_themes/default/theme_default_fm_armoury",
        "content/levels/entertainment/missions/fm_armoury_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_armoury",
        "content/levels/entertainment/missions/km_heresy_themes/darkness_01/theme_darkness_01_km_heresy",
        "content/levels/entertainment/missions/km_heresy_themes/default/theme_default_km_heresy",
        "content/levels/entertainment/missions/km_heresy_themes/ventilation_purge_01/theme_ventilation_purge_01_km_heresy",
        "content/levels/expeditions/debug/locations/location_128m_ravine_shallow_001/missions/themes/default/theme_default",
        "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/themes/darkness/theme_darkness_128",
        "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/themes/default/theme_default_128",
        "content/levels/expeditions/debug/locations/location_256_chasm_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/debug/locations/location_256_chasm_001/missions/themes/default/theme_default",
        "content/levels/expeditions/debug/locations/location_256_scarp_001/scrap_location_256/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/debug/locations/location_256_scarp_001/scrap_location_256/missions/themes/default/theme_default",
        "content/levels/expeditions/debug/locations/location_256m_dsl_test_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/debug/locations/location_256m_dsl_test_001/missions/themes/default/theme_default",
        "content/levels/expeditions/debug/locations/location_256m_pickup_test_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/debug/locations/location_256m_pickup_test_001/missions/themes/default/theme_default",
        "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/themes/darkness/theme_darkness_sz",
        "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/themes/default/theme_default_sz",
        "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/oil/location_256m_oil_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_oil_002/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/oil/location_256m_oil_003/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_oil_003/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/oil/location_256m_oil_fields_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_oil_fields_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/oil/location_256m_oil_pools_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_oil_pools_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/oil/location_256m_pipeline_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/oil/location_256m_pipeline_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_dry_basin_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_dry_basin_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_002/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_riverbed_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_riverbed_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_001/missions/themes/default/theme_default",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_001/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_003/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_003/missions/themes/dawn/theme_dawn",
        "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_003/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_train_turntable_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_train_turntable_001/missions/themes/default/theme_default",
        "content/levels/expeditions/safe_zones/wastes/sz_ventilation_shaft_001/missions/themes/darkness/theme_darkness",
        "content/levels/expeditions/safe_zones/wastes/sz_ventilation_shaft_001/missions/themes/default/theme_default",
        "content/levels/horde/missions/psykhanium_themes/default/theme_default_psykhanium",
        "content/levels/hub/hub_ship/missions/hub_ship_themes/default/theme_default_hub_ship",
        "content/levels/hub/hub_ship/missions/hub_ship_themes/hub_anniversary_01/theme_hub_anniversary",
        "content/levels/hub/hub_ship/missions/hub_ship_themes/hub_skulls_01/theme_hub_skulls",
        "content/levels/hub/hub_ship/missions/om_hub_01_themes/default/theme_default_om_hub_01",
        "content/levels/hub/hub_ship/missions/om_hub_02_themes/default/theme_default_om_hub_02",
        "content/levels/operations/no_mans_land/missions/no_mans_land_themes/default/theme_default_no_mans_land",
        "content/levels/operations/train/missions/op_train_themes/default/theme_default_op_train",
        "content/levels/prologue/missions/prologue_themes/default/prologue_theme_default",
        "content/levels/tank_foundry/missions/dm_forge_themes/assault_01/theme_assault_01_dm_forge",
        "content/levels/tank_foundry/missions/dm_forge_themes/darkness_01/theme_darkness_01_dm_forge",
        "content/levels/tank_foundry/missions/dm_forge_themes/default/theme_default_dm_forge",
        "content/levels/tank_foundry/missions/dm_forge_themes/ember_01/theme_ember_01_dm_forge",
        "content/levels/tank_foundry/missions/dm_forge_themes/hunting_grounds_01/theme_hunting_grounds_01_dm_forge",
        "content/levels/tank_foundry/missions/dm_forge_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_forge",
        "content/levels/tank_foundry/missions/fm_cargo_themes/darkness_01/theme_darkness_01_fm_cargo",
        "content/levels/tank_foundry/missions/fm_cargo_themes/default/theme_default_fm_cargo",
        "content/levels/tank_foundry/missions/fm_cargo_themes/ember_01/theme_ember_01_fm_cargo",
        "content/levels/tank_foundry/missions/fm_cargo_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_cargo",
        "content/levels/tank_foundry/missions/lm_cooling_themes/assault_01/theme_assault_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/darkness_01/theme_darkness_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/default/theme_default_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/ember_01/theme_ember_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/hunting_grounds_01/theme_hunting_grounds_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/toxic_gas_01/theme_toxic_gas_01_lm_cooling",
        "content/levels/tank_foundry/missions/lm_cooling_themes/ventilation_purge_01/theme_ventilation_purge_01_lm_cooling",
        "content/levels/throneside/missions/cm_archives_themes/darkness_01/theme_darkness_01_cm_archives",
        "content/levels/throneside/missions/cm_archives_themes/default/theme_default_cm_archives",
        "content/levels/throneside/missions/cm_archives_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_archives",
        "content/levels/throneside/missions/fm_resurgence_themes/darkness_01/theme_darkness_01_fm_resurgence",
        "content/levels/throneside/missions/fm_resurgence_themes/default/theme_default_fm_resurgence",
        "content/levels/throneside/missions/fm_resurgence_themes/toxic_gas_01/theme_toxic_gas_01_fm_resurgence",
        "content/levels/throneside/missions/fm_resurgence_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_resurgence",
        "content/levels/throneside/missions/hm_complex_themes/darkness_01/theme_darkness_01_hm_complex",
        "content/levels/throneside/missions/hm_complex_themes/default/theme_default_hm_complex",
        "content/levels/throneside/missions/hm_complex_themes/ventilation_purge_01/theme_ventilation_purge_01_hm_complex",
        "content/levels/training_grounds/missions/training_grounds_themes/default/theme_default_training_grounds",
        "content/levels/transit/deck/themes/nurgle_01/theme_nurgle_01_deck",
        "content/levels/transit/hab_a/themes/nurgle_01/theme_nurgle_01_hab_a",
        "content/levels/transit/hab_b/themes/nurgle_01/theme_nurgle_01_hab_b",
        "content/levels/transit/hab_lobby/themes/nurgle_01/theme_nurgle_01_hab_lobby",
        "content/levels/transit/hab_shaft/themes/nurgle_01/theme_nurgle_01_hab_shaft",
        "content/levels/transit/market/themes/nurgle_01/theme_nurgle_01_market",
        "content/levels/transit/missions/cm_habs_themes/darkness_01/theme_darkness_01_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/default/theme_default_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/ember_01/theme_ember_01_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/nurgle_01/theme_nurgle_01_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/toxic_gas_01/theme_toxic_gas_01_cm_habs",
        "content/levels/transit/missions/cm_habs_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_habs",
        "content/levels/transit/missions/dm_rise_themes/darkness_01/theme_darkness_01_dm_rise",
        "content/levels/transit/missions/dm_rise_themes/default/theme_default_dm_rise",
        "content/levels/transit/missions/dm_rise_themes/ember_01/theme_ember_01_dm_rise",
        "content/levels/transit/missions/dm_rise_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_rise",
        "content/levels/transit/missions/km_station_themes/assault_01/theme_assault_01_km_station",
        "content/levels/transit/missions/km_station_themes/darkness_01/theme_darkness_01_km_station",
        "content/levels/transit/missions/km_station_themes/default/theme_default_km_station",
        "content/levels/transit/missions/km_station_themes/ember_01/theme_ember_01_km_station",
        "content/levels/transit/missions/km_station_themes/gas_01/theme_gas_01_km_station",
        "content/levels/transit/missions/km_station_themes/hunting_grounds_01/theme_hunting_grounds_01_km_station",
        "content/levels/transit/missions/km_station_themes/noir_01/theme_noir_01_km_station",
        "content/levels/transit/missions/km_station_themes/nurgle_01/theme_nurgle_01_km_station",
        "content/levels/transit/missions/km_station_themes/toxic_gas_01/theme_toxic_gas_01_km_station",
        "content/levels/transit/missions/km_station_themes/ventilation_purge_01/theme_ventilation_purge_01_km_station",
        "content/levels/transit/missions/lm_rails_themes/assault_01/theme_assault_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/darkness_01/theme_darkness_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/default/theme_default_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/ember_01/theme_ember_01_junction",
        "content/levels/transit/missions/lm_rails_themes/ember_01/theme_ember_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/hunting_grounds_01/theme_hunting_grounds_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/noir_01/theme_noir_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/nurgle_01/theme_nurgle_01_lm_rails",
        "content/levels/transit/missions/lm_rails_themes/ventilation_purge_01/theme_ventilation_purge_01_lm_rails",
        "content/levels/transit/start_void/themes/nurgle_01/theme_nurgle_01_start_void",
        "content/levels/transit/streets/themes/nurgle_01/theme_nurgle_01_streets",
        "content/levels/void/missions/core_research_themes/darkness_01/theme_darkness_01_core_research",
        "content/levels/void/missions/core_research_themes/default/theme_default_core_research",
        "content/levels/void/missions/core_research_themes/ventilation_purge_01/theme_ventilation_purge_01_core_research",
        "content/levels/watertown/missions/dm_stockpile_themes/darkness_01/theme_darkness_01_dm_stockpile",
        "content/levels/watertown/missions/dm_stockpile_themes/default/theme_default_dm_stockpile",
        "content/levels/watertown/missions/dm_stockpile_themes/ember_01/theme_ember_01_dm_stockpile",
        "content/levels/watertown/missions/dm_stockpile_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_stockpile",
        "content/levels/watertown/missions/hm_cartel_themes/darkness_01/theme_darkness_01_hm_cartel",
        "content/levels/watertown/missions/hm_cartel_themes/default/theme_default_hm_cartel",
        "content/levels/watertown/missions/hm_cartel_themes/ember_01/theme_ember_01_hm_cartel",
        "content/levels/watertown/missions/hm_cartel_themes/toxic_gas_01/theme_toxic_gas_01_hm_cartel",
        "content/levels/watertown/missions/hm_cartel_themes/ventilation_purge_01/theme_ventilation_purge_01_hm_cartel",
        "content/levels/watertown/missions/km_enforcer_themes/darkness_01/theme_darkness_01_km_enforcer",
        "content/levels/watertown/missions/km_enforcer_themes/default/theme_default_km_enforcer",
        "content/levels/watertown/missions/km_enforcer_themes/ember_01/theme_ember_01_km_enforcer",
        "content/levels/watertown/missions/km_enforcer_themes/toxic_gas_01/theme_toxic_gas_01_km_enforcer",
        "content/levels/watertown/missions/km_enforcer_themes/ventilation_purge_01/theme_ventilation_purge_01_km_enforcer",
        "content/levels/watertown_twins/missions/km_enforcer_twins_themes/default/theme_default_km_enforcer_twins",
    },
    resources = {
        { "content/levels/dust/missions/dm_propaganda_themes/darkness_01/theme_darkness_01_dm_propaganda", 1 },
        { "content/levels/dust/missions/dm_propaganda_themes/default/theme_default_dm_propaganda", 2 },
        { "content/levels/dust/missions/dm_propaganda_themes/nurgle_01/theme_nurgle_01_dm_propaganda", 3 },
        { "content/levels/dust/missions/dm_propaganda_themes/toxic_gas_01/theme_toxic_gas_01_dm_propaganda", 4 },
        { "content/levels/dust/missions/hm_strain_themes/darkness_01/theme_darkness_01_hm_strain", 5 },
        { "content/levels/dust/missions/hm_strain_themes/default/theme_default_hm_strain", 6 },
        { "content/levels/dust/missions/hm_strain_themes/ember_01/theme_ember_01_hm_strain", 7 },
        { "content/levels/dust/missions/hm_strain_themes/nurgle_01/theme_nurgle_01_hm_strain", 8 },
        { "content/levels/dust/missions/hm_strain_themes/toxic_gas_01/theme_toxic_gas_01_hm_strain", 9 },
        { "content/levels/dust/missions/lm_scavenge_themes/darkness_01/theme_darkness_01_lm_scavenge", 10 },
        { "content/levels/dust/missions/lm_scavenge_themes/default/theme_default_lm_scavenge", 11 },
        { "content/levels/dust/missions/lm_scavenge_themes/toxic_gas_01/theme_toxic_gas_01_lm_scavenge", 12 },
        { "content/levels/entertainment/missions/cm_raid_themes/darkness_01/theme_darkness_01_cm_raid", 13 },
        { "content/levels/entertainment/missions/cm_raid_themes/default/theme_default_cm_raid", 14 },
        { "content/levels/entertainment/missions/cm_raid_themes/toxic_gas_01/theme_toxic_gas_01_cm_raid", 15 },
        { "content/levels/entertainment/missions/cm_raid_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_raid", 16 },
        { "content/levels/entertainment/missions/fm_armoury_themes/darkness_01/theme_darkness_01_fm_armoury", 17 },
        { "content/levels/entertainment/missions/fm_armoury_themes/default/theme_default_fm_armoury", 18 },
        { "content/levels/entertainment/missions/fm_armoury_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_armoury", 19 },
        { "content/levels/entertainment/missions/km_heresy_themes/darkness_01/theme_darkness_01_km_heresy", 20 },
        { "content/levels/entertainment/missions/km_heresy_themes/default/theme_default_km_heresy", 21 },
        { "content/levels/entertainment/missions/km_heresy_themes/ventilation_purge_01/theme_ventilation_purge_01_km_heresy", 22 },
        { "content/levels/expeditions/debug/locations/location_128m_ravine_shallow_001/missions/themes/darkness/theme_darkness", 0 },
        { "content/levels/expeditions/debug/locations/location_128m_ravine_shallow_001/missions/themes/default/theme_default", 23 },
        { "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/themes/darkness/theme_darkness_128", 24 },
        { "content/levels/expeditions/debug/locations/location_128m_theme_test_001/missions/themes/default/theme_default_128", 25 },
        { "content/levels/expeditions/debug/locations/location_256_chasm_001/missions/themes/darkness/theme_darkness", 26 },
        { "content/levels/expeditions/debug/locations/location_256_chasm_001/missions/themes/default/theme_default", 27 },
        { "content/levels/expeditions/debug/locations/location_256_scarp_001/scrap_location_256/missions/themes/darkness/theme_darkness", 28 },
        { "content/levels/expeditions/debug/locations/location_256_scarp_001/scrap_location_256/missions/themes/default/theme_default", 29 },
        { "content/levels/expeditions/debug/locations/location_256m_dsl_test_001/missions/themes/darkness/theme_darkness", 30 },
        { "content/levels/expeditions/debug/locations/location_256m_dsl_test_001/missions/themes/default/theme_default", 31 },
        { "content/levels/expeditions/debug/locations/location_256m_pickup_test_001/missions/themes/darkness/theme_darkness", 32 },
        { "content/levels/expeditions/debug/locations/location_256m_pickup_test_001/missions/themes/default/theme_default", 33 },
        { "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/themes/darkness/theme_darkness_sz", 34 },
        { "content/levels/expeditions/debug/safe_zones/safezone_theme_test_001/missions/themes/default/theme_default_sz", 35 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/darkness/theme_darkness", 36 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/dawn/theme_dawn", 37 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_001/missions/themes/default/theme_default", 38 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_002/missions/themes/darkness/theme_darkness", 39 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_002/missions/themes/default/theme_default", 40 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_003/missions/themes/darkness/theme_darkness", 41 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_003/missions/themes/default/theme_default", 42 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_fields_001/missions/themes/darkness/theme_darkness", 43 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_fields_001/missions/themes/default/theme_default", 44 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_pools_001/missions/themes/darkness/theme_darkness", 45 },
        { "content/levels/expeditions/locations/oil/location_256m_oil_pools_001/missions/themes/default/theme_default", 46 },
        { "content/levels/expeditions/locations/oil/location_256m_pipeline_001/missions/themes/darkness/theme_darkness", 47 },
        { "content/levels/expeditions/locations/oil/location_256m_pipeline_001/missions/themes/default/theme_default", 48 },
        { "content/levels/expeditions/locations/wastes/location_256m_chasm_001/missions/themes/darkness/theme_darkness", 49 },
        { "content/levels/expeditions/locations/wastes/location_256m_chasm_001/missions/themes/default/theme_default", 50 },
        { "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/darkness/theme_darkness", 51 },
        { "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/dawn/theme_dawn", 52 },
        { "content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/themes/default/theme_default", 53 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/darkness/theme_darkness", 54 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/dawn/theme_dawn", 55 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/themes/default/theme_default", 56 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/darkness/theme_darkness", 57 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/dawn/theme_dawn", 58 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/themes/default/theme_default", 59 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/darkness/theme_darkness", 60 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/dawn/theme_dawn", 61 },
        { "content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/themes/default/theme_default", 62 },
        { "content/levels/expeditions/locations/wastes/location_256m_dry_basin_001/missions/themes/darkness/theme_darkness", 63 },
        { "content/levels/expeditions/locations/wastes/location_256m_dry_basin_001/missions/themes/default/theme_default", 64 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/darkness/theme_darkness", 65 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/dawn/theme_dawn", 66 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/themes/default/theme_default", 67 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_002/missions/themes/darkness/theme_darkness", 68 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_002/missions/themes/default/theme_default", 69 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/darkness/theme_darkness", 70 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/dawn/theme_dawn", 71 },
        { "content/levels/expeditions/locations/wastes/location_256m_ravine_003/missions/themes/default/theme_default", 72 },
        { "content/levels/expeditions/locations/wastes/location_256m_riverbed_001/missions/themes/darkness/theme_darkness", 73 },
        { "content/levels/expeditions/locations/wastes/location_256m_riverbed_001/missions/themes/default/theme_default", 74 },
        { "content/levels/expeditions/locations/wastes/location_256m_underpass_001/missions/themes/darkness/theme_darkness", 75 },
        { "content/levels/expeditions/locations/wastes/location_256m_underpass_001/missions/themes/default/theme_default", 76 },
        { "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/darkness/theme_darkness", 77 },
        { "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/dawn/theme_dawn", 78 },
        { "content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/themes/default/theme_default", 79 },
        { "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/darkness/theme_darkness", 80 },
        { "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/dawn/theme_dawn", 81 },
        { "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/themes/default/theme_default", 82 },
        { "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/themes/darkness/theme_darkness", 83 },
        { "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/themes/dawn/theme_dawn", 84 },
        { "content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/themes/default/theme_default", 85 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_001/missions/themes/darkness/theme_darkness", 86 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_001/missions/themes/default/theme_default", 87 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/darkness/theme_darkness", 88 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/dawn/theme_dawn", 89 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/themes/default/theme_default", 90 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_003/missions/themes/darkness/theme_darkness", 91 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_003/missions/themes/dawn/theme_dawn", 92 },
        { "content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_003/missions/themes/default/theme_default", 93 },
        { "content/levels/expeditions/safe_zones/wastes/sz_train_turntable_001/missions/themes/darkness/theme_darkness", 94 },
        { "content/levels/expeditions/safe_zones/wastes/sz_train_turntable_001/missions/themes/default/theme_default", 95 },
        { "content/levels/expeditions/safe_zones/wastes/sz_ventilation_shaft_001/missions/themes/darkness/theme_darkness", 96 },
        { "content/levels/expeditions/safe_zones/wastes/sz_ventilation_shaft_001/missions/themes/default/theme_default", 97 },
        { "content/levels/horde/missions/psykhanium_themes/default/theme_default_psykhanium", 98 },
        { "content/levels/hub/hub_ship/missions/hub_ship_themes/default/theme_default_hub_ship", 99 },
        { "content/levels/hub/hub_ship/missions/hub_ship_themes/hub_anniversary_01/theme_hub_anniversary", 100 },
        { "content/levels/hub/hub_ship/missions/hub_ship_themes/hub_skulls_01/theme_hub_skulls", 101 },
        { "content/levels/hub/hub_ship/missions/om_hub_01_themes/default/theme_default_om_hub_01", 102 },
        { "content/levels/hub/hub_ship/missions/om_hub_02_themes/default/theme_default_om_hub_02", 103 },
        { "content/levels/operations/no_mans_land/missions/no_mans_land_themes/default/theme_default_no_mans_land", 104 },
        { "content/levels/operations/train/missions/op_train_themes/default/theme_default_op_train", 105 },
        { "content/levels/prologue/missions/prologue_themes/default/prologue_theme_default", 106 },
        { "content/levels/tank_foundry/missions/dm_forge_themes/assault_01/theme_assault_01_dm_forge", 107 },
        { "content/levels/tank_foundry/missions/dm_forge_themes/darkness_01/theme_darkness_01_dm_forge", 108 },
        { "content/levels/tank_foundry/missions/dm_forge_themes/default/theme_default_dm_forge", 109 },
        { "content/levels/tank_foundry/missions/dm_forge_themes/ember_01/theme_ember_01_dm_forge", 110 },
        { "content/levels/tank_foundry/missions/dm_forge_themes/hunting_grounds_01/theme_hunting_grounds_01_dm_forge", 111 },
        { "content/levels/tank_foundry/missions/dm_forge_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_forge", 112 },
        { "content/levels/tank_foundry/missions/fm_cargo_themes/darkness_01/theme_darkness_01_fm_cargo", 113 },
        { "content/levels/tank_foundry/missions/fm_cargo_themes/default/theme_default_fm_cargo", 114 },
        { "content/levels/tank_foundry/missions/fm_cargo_themes/ember_01/theme_ember_01_fm_cargo", 115 },
        { "content/levels/tank_foundry/missions/fm_cargo_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_cargo", 116 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/assault_01/theme_assault_01_lm_cooling", 117 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/darkness_01/theme_darkness_01_lm_cooling", 118 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/default/theme_default_lm_cooling", 119 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/ember_01/theme_ember_01_lm_cooling", 120 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/hunting_grounds_01/theme_hunting_grounds_01_lm_cooling", 121 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/toxic_gas_01/theme_toxic_gas_01_lm_cooling", 122 },
        { "content/levels/tank_foundry/missions/lm_cooling_themes/ventilation_purge_01/theme_ventilation_purge_01_lm_cooling", 123 },
        { "content/levels/throneside/missions/cm_archives_themes/darkness_01/theme_darkness_01_cm_archives", 124 },
        { "content/levels/throneside/missions/cm_archives_themes/default/theme_default_cm_archives", 125 },
        { "content/levels/throneside/missions/cm_archives_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_archives", 126 },
        { "content/levels/throneside/missions/fm_resurgence_themes/darkness_01/theme_darkness_01_fm_resurgence", 127 },
        { "content/levels/throneside/missions/fm_resurgence_themes/default/theme_default_fm_resurgence", 128 },
        { "content/levels/throneside/missions/fm_resurgence_themes/toxic_gas_01/theme_toxic_gas_01_fm_resurgence", 129 },
        { "content/levels/throneside/missions/fm_resurgence_themes/ventilation_purge_01/theme_ventilation_purge_01_fm_resurgence", 130 },
        { "content/levels/throneside/missions/hm_complex_themes/darkness_01/theme_darkness_01_hm_complex", 131 },
        { "content/levels/throneside/missions/hm_complex_themes/default/theme_default_hm_complex", 132 },
        { "content/levels/throneside/missions/hm_complex_themes/ventilation_purge_01/theme_ventilation_purge_01_hm_complex", 133 },
        { "content/levels/training_grounds/missions/training_grounds_themes/default/theme_default_training_grounds", 134 },
        { "content/levels/transit/deck/themes/nurgle_01/theme_nurgle_01_deck", 135 },
        { "content/levels/transit/hab_a/themes/nurgle_01/theme_nurgle_01_hab_a", 136 },
        { "content/levels/transit/hab_b/themes/nurgle_01/theme_nurgle_01_hab_b", 137 },
        { "content/levels/transit/hab_lobby/themes/nurgle_01/theme_nurgle_01_hab_lobby", 138 },
        { "content/levels/transit/hab_shaft/themes/nurgle_01/theme_nurgle_01_hab_shaft", 139 },
        { "content/levels/transit/market/themes/nurgle_01/theme_nurgle_01_market", 140 },
        { "content/levels/transit/missions/cm_habs_themes/darkness_01/theme_darkness_01_cm_habs", 141 },
        { "content/levels/transit/missions/cm_habs_themes/default/theme_default_cm_habs", 142 },
        { "content/levels/transit/missions/cm_habs_themes/ember_01/theme_ember_01_cm_habs", 143 },
        { "content/levels/transit/missions/cm_habs_themes/nurgle_01/theme_nurgle_01_cm_habs", 144 },
        { "content/levels/transit/missions/cm_habs_themes/toxic_gas_01/theme_toxic_gas_01_cm_habs", 145 },
        { "content/levels/transit/missions/cm_habs_themes/ventilation_purge_01/theme_ventilation_purge_01_cm_habs", 146 },
        { "content/levels/transit/missions/dm_rise_themes/darkness_01/theme_darkness_01_dm_rise", 147 },
        { "content/levels/transit/missions/dm_rise_themes/default/theme_default_dm_rise", 148 },
        { "content/levels/transit/missions/dm_rise_themes/ember_01/theme_ember_01_dm_rise", 149 },
        { "content/levels/transit/missions/dm_rise_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_rise", 150 },
        { "content/levels/transit/missions/km_station_themes/assault_01/theme_assault_01_km_station", 151 },
        { "content/levels/transit/missions/km_station_themes/darkness_01/theme_darkness_01_km_station", 152 },
        { "content/levels/transit/missions/km_station_themes/default/theme_default_km_station", 153 },
        { "content/levels/transit/missions/km_station_themes/ember_01/theme_ember_01_km_station", 154 },
        { "content/levels/transit/missions/km_station_themes/gas_01/theme_gas_01_km_station", 155 },
        { "content/levels/transit/missions/km_station_themes/hunting_grounds_01/theme_hunting_grounds_01_km_station", 156 },
        { "content/levels/transit/missions/km_station_themes/noir_01/theme_noir_01_km_station", 157 },
        { "content/levels/transit/missions/km_station_themes/nurgle_01/theme_nurgle_01_km_station", 158 },
        { "content/levels/transit/missions/km_station_themes/toxic_gas_01/theme_toxic_gas_01_km_station", 159 },
        { "content/levels/transit/missions/km_station_themes/ventilation_purge_01/theme_ventilation_purge_01_km_station", 160 },
        { "content/levels/transit/missions/lm_rails_themes/assault_01/theme_assault_01_lm_rails", 161 },
        { "content/levels/transit/missions/lm_rails_themes/darkness_01/theme_darkness_01_lm_rails", 162 },
        { "content/levels/transit/missions/lm_rails_themes/default/theme_default_lm_rails", 163 },
        { "content/levels/transit/missions/lm_rails_themes/ember_01/theme_ember_01_junction", 164 },
        { "content/levels/transit/missions/lm_rails_themes/ember_01/theme_ember_01_lm_rails", 165 },
        { "content/levels/transit/missions/lm_rails_themes/hunting_grounds_01/theme_hunting_grounds_01_lm_rails", 166 },
        { "content/levels/transit/missions/lm_rails_themes/noir_01/theme_noir_01_lm_rails", 167 },
        { "content/levels/transit/missions/lm_rails_themes/nurgle_01/theme_nurgle_01_lm_rails", 168 },
        { "content/levels/transit/missions/lm_rails_themes/ventilation_purge_01/theme_ventilation_purge_01_lm_rails", 169 },
        { "content/levels/transit/start_void/themes/nurgle_01/theme_nurgle_01_start_void", 170 },
        { "content/levels/transit/streets/themes/nurgle_01/theme_nurgle_01_streets", 171 },
        { "content/levels/void/missions/core_research_themes/darkness_01/theme_darkness_01_core_research", 172 },
        { "content/levels/void/missions/core_research_themes/default/theme_default_core_research", 173 },
        { "content/levels/void/missions/core_research_themes/ventilation_purge_01/theme_ventilation_purge_01_core_research", 174 },
        { "content/levels/watertown/missions/dm_stockpile_themes/darkness_01/theme_darkness_01_dm_stockpile", 175 },
        { "content/levels/watertown/missions/dm_stockpile_themes/default/theme_default_dm_stockpile", 176 },
        { "content/levels/watertown/missions/dm_stockpile_themes/ember_01/theme_ember_01_dm_stockpile", 177 },
        { "content/levels/watertown/missions/dm_stockpile_themes/ventilation_purge_01/theme_ventilation_purge_01_dm_stockpile", 178 },
        { "content/levels/watertown/missions/hm_cartel_themes/darkness_01/theme_darkness_01_hm_cartel", 179 },
        { "content/levels/watertown/missions/hm_cartel_themes/default/theme_default_hm_cartel", 180 },
        { "content/levels/watertown/missions/hm_cartel_themes/ember_01/theme_ember_01_hm_cartel", 181 },
        { "content/levels/watertown/missions/hm_cartel_themes/toxic_gas_01/theme_toxic_gas_01_hm_cartel", 182 },
        { "content/levels/watertown/missions/hm_cartel_themes/ventilation_purge_01/theme_ventilation_purge_01_hm_cartel", 183 },
        { "content/levels/watertown/missions/km_enforcer_themes/darkness_01/theme_darkness_01_km_enforcer", 184 },
        { "content/levels/watertown/missions/km_enforcer_themes/default/theme_default_km_enforcer", 185 },
        { "content/levels/watertown/missions/km_enforcer_themes/ember_01/theme_ember_01_km_enforcer", 186 },
        { "content/levels/watertown/missions/km_enforcer_themes/toxic_gas_01/theme_toxic_gas_01_km_enforcer", 187 },
        { "content/levels/watertown/missions/km_enforcer_themes/ventilation_purge_01/theme_ventilation_purge_01_km_enforcer", 188 },
        { "content/levels/watertown_twins/missions/km_enforcer_twins_themes/default/theme_default_km_enforcer_twins", 189 },
    },
}
