local mod = get_mod("LIDAR")

return {
	name = mod:localize("mod_name"),
	description = "LIDAR mod. Can crash game if you touch settings while stuff is drawn (also while not). I recommended you find the settings you like THEN have your fun. Once you find a setting that you and your pc likes its kinda stable.",
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "scan_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "lidar_scan",
			},
			{
				setting_id = "radial_scan_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "radial_scan",
			},
			{
				setting_id = "darkness_enabled",
				type = "checkbox",
				default_value = false,
			},
			{
				setting_id = "gamma_level",
				type = "numeric",
				default_value = -10,
				range = { -15, 0 },
				decimals_number = 0,
			},
			{
				setting_id = "h_res",
				type = "numeric",
				default_value = 80,
				range = { 10, 300 },
				decimals_number = 0,
			},
			{
				setting_id = "v_res",
				type = "numeric",
				default_value = 50,
				range = { 10, 200 },
				decimals_number = 0,
			},
			{
				setting_id = "h_fov",
				type = "numeric",
				default_value = 90,
				range = { 10, 180 },
				decimals_number = 0,
			},
			{
				setting_id = "v_fov",
				type = "numeric",
				default_value = 60,
				range = { 10, 180 },
				decimals_number = 0,
			},
			{
				setting_id = "max_range",
				type = "numeric",
				default_value = 30,
				range = { 5, 200 },
				decimals_number = 0,
			},
			{
				setting_id = "dot_size",
				type = "numeric",
				default_value = 5,
				range = { 1, 100 },
				decimals_number = 0,
			},
			{
				setting_id = "dot_duration",
				type = "numeric",
				default_value = 15,
				range = { 1, 120 },
				decimals_number = 0,
			},
			{
				setting_id = "color_scheme",
				type = "dropdown",
				default_value = "classic",
				options = {
					{ text = "opt_scheme_classic", value = "classic" },
					{ text = "opt_scheme_mono", value = "mono" },
					{ text = "opt_scheme_infrared", value = "infrared" },
					{ text = "opt_scheme_amber", value = "amber" },
					{ text = "opt_scheme_toxin", value = "toxin" },
					{ text = "opt_scheme_rainbow", value = "rainbow" },
				},
			},
			{
				setting_id = "lines_per_dot",
				type = "dropdown",
				default_value = 3,
				options = {
					{ text = "opt_one_line", value = 1 },
					{ text = "opt_two_lines", value = 2 },
					{ text = "opt_three_lines", value = 3 },
				},
			},
			{
				setting_id = "rows_per_frame",
				type = "numeric",
				default_value = 2,
				range = { 1, 50 },
				decimals_number = 0,
			},
			{
				setting_id = "max_dots",
				type = "numeric",
				default_value = 35000,
				range = { 1000, 150000 },
				decimals_number = 0,
			},
			{
				setting_id = "chunked_rebuild",
				type = "checkbox",
				default_value = false,
			},
			{
				setting_id = "rebuild_per_frame",
				type = "numeric",
				default_value = 1500,
				range = { 250, 10000 },
				decimals_number = 0,
			},
			{
				setting_id = "auto_pulse",
				type = "checkbox",
				default_value = false,
			},
			{
				setting_id = "auto_pulse_mode",
				type = "dropdown",
				default_value = "radial",
				options = {
					{ text = "opt_pulse_radial", value = "radial" },
					{ text = "opt_pulse_fov", value = "fov" },
				},
			},
			{
				setting_id = "auto_pulse_interval",
				type = "numeric",
				default_value = 6,
				range = { 1, 60 },
				decimals_number = 1,
			},
			{
				setting_id = "recycle_oldest",
				type = "checkbox",
				default_value = true,
			},
		},
	},
}
